sudo: required

language: node_js

node_js: 6.9.5


branches:
  only:
    - staging
    - master

addons:
  hosts:
    - localhost

before_script:
  - npm install -g grunt-cli

script:
  - grunt coverage
